app:
  address: "127.0.0.1"
  port: 8080

jwt: 
  secretKey: "jwtsupersecretkey"

postgres: 
  host: "localhost"
  port: 5432
  database: "brate_test"

  clients:
    currency: 
      username: 'postgres'
      password: 'QScvWoBr15I2XDF1bWLLDA'