app:
  address: "127.0.0.1"
  port: 8080

jwt: 
  secretKey: "jwtsupersecretkey"

postgres: 
  host: "localhost"
  port: 5432
  database: "brate_dev"

  clients:
    currency: 
      username: 'postgres'
      password: 'QScvWoBr15I2XDF1bWLLDA'
      pool_size: 10

bcrypt: 
  saltRounds: 12
  expiryAfter: 14400

currency_rate:
  url: 'http://data.fixer.io/api'
  
  api_keys:
    - '0f15e30f695326c081ddbf30424e019e'
    